apiVersion: v1
kind: Pod
metadata:
  name: go-echo-probe
spec:
  containers:
    - name: go-echo-probe
      image: kowlon/go-echo:v1
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: "10m"
          memory: "32Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      startupProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3