apiVersion: stackgres.io/v1
kind: SGScript
metadata:
  name: create-db-script-product
  namespace: postgresql
spec:
  managedVersions: true
  continueOnError: false
  scripts:
  - name: create-database
    script: |
      CREATE DATABASE product_db WITH OWNER postgres;

      


