version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ecommerce         # Set your desired PostgreSQL username
      POSTGRES_PASSWORD: ecommerce # Set your desired PostgreSQL password
      POSTGRES_DB: ecommerce             # Set your desired PostgreSQL database name
    ports:
      - "5432:5432"  # Exposing port 5432 for external access
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persisting the data
      - ./init:/docker-entrypoint-initdb.d/     # Mount the init script
    networks:
      - postgres-network
    restart: always

volumes:
  postgres-data:  # Named volume for PostgreSQL data

networks:
  postgres-network:
    driver: bridge
