apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-2-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-echo
  template:
    metadata:
      labels:
        app: go-echo
    spec:
      containers:
      - name: go-echo
        image: kowlon/go-echo:v2
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: go-echo-service
spec:
  selector:
    app: go-echo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer


