---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-kowlon-my-id-wc
  namespace: istio-ingress
spec:
  secretName: apps-kowlon-my-id-wc-crt
  dnsNames:
    - "*.apps.kowlon.my.id"
  issuerRef:
    name: production-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
