apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  namespace: quota
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-echo
  template:
    metadata:
      labels:
        app: go-echo
    spec:
      containers:
        - name: go-echo
          image: kowlon/go-echo:v2
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "20m"
              memory: "25Mi"
            limits:
              cpu: "50m"
              memory: "64Mi"
