apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-echo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go-echo
  template:
    metadata:
      labels:
        app: go-echo
    spec:
      containers:
      - name: go-echo
        image: kowlon/go-echo:v2
        ports:
        - containerPort: 8080
