apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- virtual-service.yaml
namespace: production
images:
- name: kowlon/go-echo
  newName: kowlon/ecommerce-user
  newTag: latest
patches:
- path: env-patch.yaml
  target:
    kind: Deployment
    name: ecommerce-user
    namespace: production
