apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  iops: "3000"        # Keep this if you want a specific IOPS value
  throughput: "125"   # Optional, set the desired throughput in MiB/s
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
