---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echov2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echov2
      version: v2
  template:
    metadata:
      labels:
        app: echov2
        version: v2
        istio: monitor
    spec:
      containers:
        - image: kowlon/go-echo:v2
          imagePullPolicy: Always
          name: echov2
          env:
            - name: env
              value: production
          ports:
            - name: http
              containerPort: 8080
