apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS  # Standard locally-redundant storage
  location: eastus
  storageaccounttype: Standard_LRS
