apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "ecommerce_product_production"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:k0wl0n/go-ecommerce-product.git
    targetRevision: HEAD
    path: overlay/production/go-ecommerce-product
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true