{
 "title": "Kubernetes Dashboard",
 "description": "Summary metrics about kube-state-metrics v2 version(https://github.com/kubernetes/kube-state-metrics); Referenced 6417",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "node",
    "query": "label_values(kube_node_info{cluster=~\"$cluster\"}, node)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_created{cluster=~\"$cluster\"}, namespace)"
   },
   { "name": "datasource", "query": "vmcluster" },
   {
    "name": "deployment",
    "label": "deployment",
    "query": {
     "query": "label_values({cluster=\"$cluster\", namespace=\"$namespace\"},deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Deployment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "WITH(\r\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\r\n    deploymentName = avg by (deployment, pod) (\r\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \r\n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment) \r\n    ),\r\n    containerRequest = avg by (deployment, container) (deploymentName * on (pod) group_right(deployment) avg(kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"$deployment.*\", namespace=~\"$namespace\"}) by (pod, container))\r\n)\r\ncontainerRequest * 1000 ",
     "legendFormat": "request: {{ deployment }}"
    },
    {
     "expr": "WITH(\r\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\r\n    deploymentName = avg by (deployment, pod) (\r\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \r\n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment) \r\n    ),\r\n    containerLimit = avg by (deployment, container) (deploymentName * on (pod) group_right(deployment) avg(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"$deployment.*\", namespace=~\"$namespace\"}) by (pod, container))\r\n)\r\ncontainerLimit * 1000 ",
     "legendFormat": "limit: {{ deployment }}"
    },
    {
     "expr": "WITH(\r\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\r\n    deploymentName = avg by (deployment, pod) (\r\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \r\n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment) \r\n    ),\r\n    containerUsage = avg by (deployment, container) (deploymentName * on (pod) group_right(deployment) sum(rate(container_cpu_usage_seconds_total{pod=~\"$deployment.*\",namespace=~\"$namespace\"}[$__rate_interval])) by (pod,container))\r\n)\r\ncontainerUsage * 1000 ",
     "legendFormat": "usage: {{ deployment }}"
    }
   ]
  },
  {
   "title": "Memory Usage Deployment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "WITH(\r\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\r\n    deploymentName = avg by (deployment, pod) (\r\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \r\n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment) \r\n    ),\r\n    containerRequest = avg by (deployment, container) (deploymentName * on (pod) group_right(deployment) avg(kube_pod_container_resource_requests{resource=\"memory\",pod=~\"$deployment.*\", namespace=~\"$namespace\",container!=\"istio-proxy\"}) by (container, pod))\r\n)\r\ncontainerRequest",
     "legendFormat": "request: {{ deployment }}"
    },
    {
     "expr": "WITH(\r\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\r\n    deploymentName = avg by (deployment, pod) (\r\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \r\n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment) \r\n    ),\r\n    containerLimit = avg by (deployment, container) (deploymentName * on (pod) group_right(deployment) avg(kube_pod_container_resource_limits{resource=\"memory\",pod=~\"$deployment.*\", namespace=~\"$namespace\"}) by (container, pod))\r\n)\r\ncontainerLimit",
     "legendFormat": "limit: {{ deployment }}"
    },
    {
     "expr": "WITH(\r\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\r\n    deploymentName = avg by (deployment, pod) (\r\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \r\n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment) \r\n    ),\r\n    containerUsage = avg by (deployment, container) (deploymentName * on (pod) group_right(deployment) avg(container_memory_working_set_bytes{pod=~\"$deployment.*\",namespace=~\"$namespace\"}) by (container, pod))\r\n)\r\ncontainerUsage",
     "legendFormat": "usage: {{ deployment }}"
    }
   ]
  },
  {
   "title": "Pods State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "WITH(\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\n    deploymentName = avg by (deployment, pod) (\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment)\n    ),\n    podStatusPhase = sum by (deployment, phase) (deploymentName * on (pod) group_right(deployment) avg(kube_pod_status_phase{commonVars, pod=~\"$deployment.*\", phase=\"Running\"}) by (pod, phase))\n)\npodStatusPhase",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "WITH(\r\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\r\n    deploymentName = avg by (deployment, pod) (\r\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \r\n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment)\r\n    ),\r\n    podStatusPhase = sum by (deployment, phase) (deploymentName * on (pod) group_right(deployment) avg(kube_pod_status_phase{commonVars, pod=~\"$deployment.*\", phase=\"Pending\"}) by (pod, phase))\r\n)\r\npodStatusPhase",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "WITH(\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\n    deploymentName = avg by (deployment, pod) (\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment)\n    ),\n    podStatusClbo = sum by (deployment, phase) (deploymentName * on (pod) group_right(deployment) increase(kube_pod_container_status_restarts_total{commonVars, pod=~\"$deployment.*\"}[5m]))\n)\npodStatusClbo ",
     "legendFormat": "CrashLoopBackOff"
    },
    {
     "expr": "WITH(\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\n    deploymentName = avg by (deployment, pod) (\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment)\n    ),\n    podStatusPhase = sum by (deployment, phase) (deploymentName * on (pod) group_right(deployment) avg(kube_pod_status_phase{commonVars, pod=~\"$deployment.*\", phase=\"Failed\"}) by (pod, phase))\n)\npodStatusPhase",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "WITH(\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\n    deploymentName = avg by (deployment, pod) (\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment)\n    ),\n    podStatusPhase = sum by (deployment, phase) (deploymentName * on (pod) group_right(deployment) avg(kube_pod_status_phase{commonVars, pod=~\"$deployment.*\", phase=\"Unknown\"}) by (pod, phase))\n)\npodStatusPhase",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"$deployment\"}"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Pod Requested",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=~\"$cluster\",node=~\"$node\"}) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"pods\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Requested",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\",node=~\"$node\"})/ sum(kube_node_status_allocatable{node=~\"$node\",cluster=~\"$cluster\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory  Requested",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\",node=~\"$node\"}) / sum(kube_node_status_allocatable{node=~\"$node\",cluster=~\"$cluster\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"pods\",node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_pod_info{node=~\"$node\",cluster=~\"$cluster\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{node=~\"$node\",cluster=~\"$cluster\",resource=\"cpu\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",cluster=~\"$cluster\",resource=\"cpu\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\",node=~\"$node\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\",node=~\"$node\"})",
     "legendFormat": "limited"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",cluster=~\"$cluster\",resource=\"memory\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{node=~\"$node\",cluster=~\"$cluster\",resource=\"memory\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\",node=~\"$node\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\",node=~\"$node\"})",
     "legendFormat": "limited"
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number Of Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{cluster=~\"staging\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Node NotReady",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_node_status_condition{cluster=~\"$cluster\",condition=\"Ready\",status=\"false\"}==1",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Pressure",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"DiskPressure\",cluster=~\"$cluster\",status=\"true\"}==1",
     "legendFormat": "{{node}} {{condition}}"
    },
    {
     "expr": "kube_node_status_condition{condition=\"MemoryPressure\",node=~\"$node\",cluster=~\"$cluster\",status=\"true\"}==1",
     "legendFormat": "{{node}} {{condition}}"
    },
    {
     "expr": "kube_node_status_condition{condition=~\"PIDPressure\",node=~\"$node\",cluster=~\"$cluster\",status=\"true\"}==1",
     "legendFormat": "{{node}} {{condition}}"
    }
   ]
  },
  {
   "title": "node number",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_info{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\",cluster=~\"$cluster\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Statefuleset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Statefulset Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\",cluster=~\"$cluster\"}",
     "legendFormat": "{{ statefulset}}"
    }
   ]
  },
  {
   "title": "Statefulset replicas",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\",cluster=~\"$cluster\"}/kube_statefulset_status_replicas{namespace=~\"$namespace\",cluster=~\"$cluster\"}*100",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods restart in 30m",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",cluster=~\"$cluster\"}[30m])>1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Evicted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_status_reason{cluster=~\"$cluster\",namespace=~\"$namespace\", reason=\"Evicted\"}==1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Containers Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",cluster=~\"$cluster\"}[30m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\" ,cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "HPA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "hpa",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "current_{{hpa}}"
      },
      {
       "expr": "kube_hpa_spec_max_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "max_{{hpa}}"
      },
      {
       "expr": "kube_hpa_spec_min_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "min_{{hpa}}"
      }
     ]
    },
    {
     "title": "total-hpa-current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_hpa_status_current_replicas{hpa=~\".*\"})",
       "legendFormat": "kube_hpa_status_current_replicas"
      }
     ]
    },
    {
     "title": "current==max",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{hpa=~\".*\"} == kube_hpa_spec_max_replicas{hpa=~\".*\"}",
       "legendFormat": "{{hpa}}"
      }
     ]
    },
    {
     "title": "current==min",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{hpa=~\".*\"} == kube_hpa_spec_min_replicas{hpa=~\".*\"}",
       "legendFormat": "{{hpa}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Job last success time from now",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 68 },
   "targets": [
    {
     "expr": "(time()-kube_job_status_completion_time{namespace=~\"$namespace\",cluster=~\"$cluster\"})/60/60/24>1",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Job failed",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 68 },
   "targets": [
    {
     "expr": "kube_job_status_failed{namespace=~\"$namespace\",cluster=~\"$cluster\"}>1",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Jobs Active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "PVC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "pvc is bound",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\"}==1)",
     "legendFormat": "{{persistentvolumeclaim=}}"
    }
   ]
  },
  {
   "title": "pvc is not bound",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase!=\"Bound\"}==1)",
     "legendFormat": "{{persistentvolumeclaim=}}"
    }
   ]
  },
  {
   "title": "pvc",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes/1024/1024/1024",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}