---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo1
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo1
      version: v2
  template:
    metadata:
      labels:
        app: echo1
        version: v2
        istio: monitor
    spec:
      containers:
        - image: kowlon/go-echo:v2
          imagePullPolicy: Always
          name: echo1
          env:
            - name: SERVICE
              value: echo1
            - name: VERSION
              value: v2
          ports:
            - name: http
              containerPort: 8080
