apiVersion: stackgres.io/v1
kind: SGScript
metadata:
  name: create-db-script-order
  namespace: postgresql
spec:
  managedVersions: true
  continueOnError: false
  scripts:
  - name: create-database
    script: |
      CREATE DATABASE order_db WITH OWNER postgres;

      


